### PR TITLE
updates for eslint3 and plugin6

### PR DESCRIPTION
**Pull request by snypelife**

### CODE REVIEW

**Comment by snypelife** [comment]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-mount-set-state.md

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-update-set-state.md

**Comment by darrenmce** [comment]
i think we want the default behaviour (same behaviour as old `allow-in-func`), not the `disallow-in-func`

**Comment by snypelife** [comment]
so i guess just remove the value all together? so its just 
```
"react/no-did-mount-set-state": 2,
 "react/no-did-update-set-state": 2,
```

**Comment by darrenmce** [comment]
sounds good, lets get that in and bump our version, which is a tag from what i remember

**Comment by snypelife** [comment]
awesome, will do

**Pull request merged**
